-- ============================================================================
-- Budget Tracker — Supabase schema
-- ----------------------------------------------------------------------------
-- Tables, RLS policies, indexes, triggers, and the cycle-apply RPC.
-- Run this in the Supabase SQL editor (or via `supabase db push`).
-- All tables are owned by `auth.uid()` and isolated via Row Level Security.
-- ============================================================================

-- Extensions ------------------------------------------------------------------
create extension if not exists "pgcrypto";

-- Enums -----------------------------------------------------------------------
do $$ begin
  create type tx_type as enum ('income', 'expense');
exception when duplicate_object then null; end $$;

-- ============================================================================
-- profiles  (1:1 with auth.users)
-- ============================================================================
create table if not exists public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  username     text not null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ============================================================================
-- wallets  (one per user; active + investment balance)
-- ============================================================================
create table if not exists public.wallets (
  user_id      uuid primary key references auth.users(id) on delete cascade,
  active       bigint not null default 0,
  investment   bigint not null default 0,
  updated_at   timestamptz not null default now()
);

-- ============================================================================
-- categories
-- ============================================================================
create table if not exists public.categories (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  name         text not null,
  type         tx_type not null,
  created_at   timestamptz not null default now()
);
create index if not exists categories_user_idx on public.categories(user_id);
create unique index if not exists categories_user_name_type_uniq
  on public.categories(user_id, lower(name), type);

-- ============================================================================
-- fixed_incomes
-- ============================================================================
create table if not exists public.fixed_incomes (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  category_id   uuid not null references public.categories(id) on delete restrict,
  amount        bigint not null check (amount > 0),
  day_of_month  int   not null check (day_of_month between 1 and 31),
  created_at    timestamptz not null default now()
);
create index if not exists fixed_incomes_user_idx on public.fixed_incomes(user_id);

-- ============================================================================
-- fixed_expenses  (each one is bound to a fixed income's date)
-- ============================================================================
create table if not exists public.fixed_expenses (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  category_id       uuid not null references public.categories(id) on delete restrict,
  fixed_income_id   uuid not null references public.fixed_incomes(id) on delete cascade,
  amount            bigint not null check (amount > 0),
  created_at        timestamptz not null default now()
);
create index if not exists fixed_expenses_user_idx on public.fixed_expenses(user_id);
create index if not exists fixed_expenses_income_idx on public.fixed_expenses(fixed_income_id);

-- ============================================================================
-- transactions
-- ============================================================================
create table if not exists public.transactions (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  category_id   uuid not null references public.categories(id) on delete restrict,
  type          tx_type not null,
  amount        bigint not null check (amount > 0),
  note          text not null default '',
  occurred_at   timestamptz not null default now(),
  -- when this row was generated by a fixed_income / fixed_expense, we record
  -- the source so we can prevent double-applying a cycle:
  fixed_source_id   uuid,
  fixed_cycle_key   text,    -- e.g. '2026-04' for the April cycle
  created_at        timestamptz not null default now()
);
create index if not exists transactions_user_occurred_idx
  on public.transactions(user_id, occurred_at desc);
create index if not exists transactions_user_category_idx
  on public.transactions(user_id, category_id);
create unique index if not exists transactions_fixed_cycle_uniq
  on public.transactions(user_id, fixed_source_id, fixed_cycle_key)
  where fixed_source_id is not null;

-- ============================================================================
-- updated_at triggers
-- ============================================================================
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

drop trigger if exists wallets_touch on public.wallets;
create trigger wallets_touch before update on public.wallets
  for each row execute function public.touch_updated_at();

-- ============================================================================
-- New-user bootstrap
--   Auto-creates a profile + empty wallet when a new auth user signs up.
-- ============================================================================
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, username)
  values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;

  insert into public.wallets (user_id) values (new.id)
  on conflict (user_id) do nothing;

  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================================
-- apply_cycles(now timestamptz)
--   Idempotent. For each fixed income/expense whose cycle date has passed
--   in the current month and hasn't been applied, insert a transaction
--   and adjust the wallet balance. Safe to call repeatedly (e.g. on login,
--   from a cron edge function, or from a client mount effect).
-- ============================================================================
create or replace function public.apply_cycles(p_now timestamptz default now())
returns void language plpgsql security definer set search_path = public as $$
declare
  v_user uuid := auth.uid();
  rec    record;
  v_cycle_date date;
  v_cycle_key  text;
  v_eom int;
  v_day int;
begin
  if v_user is null then
    raise exception 'apply_cycles: not authenticated';
  end if;

  -- Fixed income
  for rec in
    select fi.id, fi.amount, fi.day_of_month, fi.category_id
    from public.fixed_incomes fi
    where fi.user_id = v_user
  loop
    v_eom := extract(day from (date_trunc('month', p_now) + interval '1 month - 1 day'))::int;
    v_day := least(rec.day_of_month, v_eom);
    v_cycle_date := make_date(
      extract(year from p_now)::int,
      extract(month from p_now)::int,
      v_day
    );
    -- if today is before the cycle day, the current cycle is last month's
    if p_now::date < v_cycle_date then
      v_cycle_date := (v_cycle_date - interval '1 month')::date;
    end if;
    v_cycle_key := to_char(v_cycle_date, 'YYYY-MM');

    insert into public.transactions
      (user_id, category_id, type, amount, note, occurred_at, fixed_source_id, fixed_cycle_key)
    values
      (v_user, rec.category_id, 'income', rec.amount, 'Fixed income',
       v_cycle_date::timestamptz, rec.id, v_cycle_key)
    on conflict do nothing;

    if found then
      update public.wallets
         set active = active + rec.amount
       where user_id = v_user;
    end if;
  end loop;

  -- Fixed expenses (date inherited from linked fixed income)
  for rec in
    select fe.id, fe.amount, fe.category_id, fi.day_of_month
    from public.fixed_expenses fe
    join public.fixed_incomes fi on fi.id = fe.fixed_income_id
    where fe.user_id = v_user
  loop
    v_eom := extract(day from (date_trunc('month', p_now) + interval '1 month - 1 day'))::int;
    v_day := least(rec.day_of_month, v_eom);
    v_cycle_date := make_date(
      extract(year from p_now)::int,
      extract(month from p_now)::int,
      v_day
    );
    if p_now::date < v_cycle_date then
      v_cycle_date := (v_cycle_date - interval '1 month')::date;
    end if;
    v_cycle_key := to_char(v_cycle_date, 'YYYY-MM');

    insert into public.transactions
      (user_id, category_id, type, amount, note, occurred_at, fixed_source_id, fixed_cycle_key)
    values
      (v_user, rec.category_id, 'expense', rec.amount, 'Fixed expense',
       v_cycle_date::timestamptz, rec.id, v_cycle_key)
    on conflict do nothing;

    if found then
      update public.wallets
         set active = active - rec.amount
       where user_id = v_user;
    end if;
  end loop;
end $$;

-- ============================================================================
-- Wallet maintenance: keep `active` in sync when transactions change.
--   Note: apply_cycles already updates the wallet on auto-insert, but these
--   triggers cover all manual inserts/updates/deletes too.
-- ============================================================================
create or replace function public.tx_wallet_delta()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_delta bigint := 0;
begin
  if (TG_OP = 'INSERT') then
    -- skip if this insert came from apply_cycles (it already moved the wallet)
    if new.fixed_source_id is not null then
      return new;
    end if;
    v_delta := case when new.type = 'income' then new.amount else -new.amount end;
    update public.wallets set active = active + v_delta where user_id = new.user_id;
    return new;

  elsif (TG_OP = 'UPDATE') then
    -- amount/type change → adjust by the difference
    v_delta := case when old.type = 'income' then -old.amount else old.amount end
             + case when new.type = 'income' then  new.amount else -new.amount end;
    if v_delta <> 0 then
      update public.wallets set active = active + v_delta where user_id = new.user_id;
    end if;
    return new;

  elsif (TG_OP = 'DELETE') then
    v_delta := case when old.type = 'income' then -old.amount else old.amount end;
    update public.wallets set active = active + v_delta where user_id = old.user_id;
    return old;
  end if;
  return null;
end $$;

drop trigger if exists tx_wallet_ins on public.transactions;
create trigger tx_wallet_ins after insert on public.transactions
  for each row execute function public.tx_wallet_delta();

drop trigger if exists tx_wallet_upd on public.transactions;
create trigger tx_wallet_upd after update on public.transactions
  for each row execute function public.tx_wallet_delta();

drop trigger if exists tx_wallet_del on public.transactions;
create trigger tx_wallet_del after delete on public.transactions
  for each row execute function public.tx_wallet_delta();

-- ============================================================================
-- Row Level Security
-- ============================================================================
alter table public.profiles        enable row level security;
alter table public.wallets         enable row level security;
alter table public.categories      enable row level security;
alter table public.fixed_incomes   enable row level security;
alter table public.fixed_expenses  enable row level security;
alter table public.transactions    enable row level security;

-- profiles: a user sees & edits only their own row
drop policy if exists "profiles self read"   on public.profiles;
drop policy if exists "profiles self write"  on public.profiles;
create policy "profiles self read"  on public.profiles for select using (id = auth.uid());
create policy "profiles self write" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

-- wallets: same pattern; insert is handled by the new-user trigger
drop policy if exists "wallets self read"   on public.wallets;
drop policy if exists "wallets self write"  on public.wallets;
create policy "wallets self read"  on public.wallets for select using (user_id = auth.uid());
create policy "wallets self write" on public.wallets for update using (user_id = auth.uid()) with check (user_id = auth.uid());

-- generic per-user policy for the rest
do $$
declare
  t text;
begin
  for t in select unnest(array['categories','fixed_incomes','fixed_expenses','transactions'])
  loop
    execute format('drop policy if exists "%s read"   on public.%I', t, t);
    execute format('drop policy if exists "%s insert" on public.%I', t, t);
    execute format('drop policy if exists "%s update" on public.%I', t, t);
    execute format('drop policy if exists "%s delete" on public.%I', t, t);

    execute format($f$create policy "%s read"   on public.%I for select using (user_id = auth.uid())$f$, t, t);
    execute format($f$create policy "%s insert" on public.%I for insert with check (user_id = auth.uid())$f$, t, t);
    execute format($f$create policy "%s update" on public.%I for update using (user_id = auth.uid()) with check (user_id = auth.uid())$f$, t, t);
    execute format($f$create policy "%s delete" on public.%I for delete using (user_id = auth.uid())$f$, t, t);
  end loop;
end $$;

-- ============================================================================
-- Done. Useful follow-ups:
--   • Schedule `select public.apply_cycles();` daily via pg_cron / edge cron
--     so cycles fire without requiring the user to open the app.
--   • Add a view `v_category_spend_current_cycle(user_id, category_id, spent)`
--     if you want server-side analytics aggregates.
-- ============================================================================
